env = Environment()

env.Append(CCFLAGS='-g',
	   CXXFLAGS="-std=c++11",
           CPPPATH=['/usr/local/include'],
           LIBS=['cantera', 'sundials_cvodes', 'sundials_ida', 'sundials_nvecserial', 'lapack', 'blas'],
           LIBPATH=['/usr/local/lib'],
           LINKFLAGS=['-g', '-pthread'])

diffflame = env.Program('main.out', 'main.cpp')
Default(diffflame)
